version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    ports:
      - '80:80'

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  redis-data:
